//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PkudatYomanWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com/ladpc/fi/pkudot/services", ConfigurationName="PkudatYomanWebService.PkudatYomanWS")]
    public interface PkudatYomanWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ShuratPkuda))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreatePkudaRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PkudatYomanWebService.CreatePkudatYomanResponse createPkudatYoman(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatYomanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<PkudatYomanWebService.CreatePkudatYomanResponse> createPkudatYomanAsync(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatYomanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ShuratPkuda))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreatePkudaRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PkudatYomanWebService.CreatePkudatZikuyResponse createPkudatZikuy(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatZikuyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<PkudatYomanWebService.CreatePkudatZikuyResponse> createPkudatZikuyAsync(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatZikuyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.commons.services")]
    public partial class SystemHeader
    {
        
        private int customerField;
        
        private int recipientField;
        
        private int senderField;
        
        private string tokenField;
        
        private string tranIDField;
        
        private string userIdField;
        
        private string userPassField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TranID
        {
            get
            {
                return this.tranIDField;
            }
            set
            {
                this.tranIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string UserPass
        {
            get
            {
                return this.userPassField;
            }
            set
            {
                this.userPassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.commons.services")]
    public partial class Globals
    {
        
        private string fileNetTokenField;
        
        private string iisIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string FileNetToken
        {
            get
            {
                return this.fileNetTokenField;
            }
            set
            {
                this.fileNetTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string IisIp
        {
            get
            {
                return this.iisIpField;
            }
            set
            {
                this.iisIpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.commons.services")]
    public partial class Msg
    {
        
        private string rcMessageField;
        
        private int rcNumberField;
        
        private int rcOwnerField;
        
        private int rcTypeField;
        
        private string rcVersionField;
        
        private string rcFieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string RcMessage
        {
            get
            {
                return this.rcMessageField;
            }
            set
            {
                this.rcMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RcNumber
        {
            get
            {
                return this.rcNumberField;
            }
            set
            {
                this.rcNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RcOwner
        {
            get
            {
                return this.rcOwnerField;
            }
            set
            {
                this.rcOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RcType
        {
            get
            {
                return this.rcTypeField;
            }
            set
            {
                this.rcTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string RcVersion
        {
            get
            {
                return this.rcVersionField;
            }
            set
            {
                this.rcVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RcFieldName
        {
            get
            {
                return this.rcFieldNameField;
            }
            set
            {
                this.rcFieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePkudatYomanResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePkudatZikuyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.commons.services")]
    public partial class ReturnObject
    {
        
        private Msg msgField;
        
        private Globals globalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Msg Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Globals Globals
        {
            get
            {
                return this.globalsField;
            }
            set
            {
                this.globalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePkudatZikuyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class CreatePkudatYomanResponse : ReturnObject
    {
        
        private System.Nullable<long> misparPkudaField;
        
        private System.Nullable<int> shanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> MisparPkuda
        {
            get
            {
                return this.misparPkudaField;
            }
            set
            {
                this.misparPkudaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Shana
        {
            get
            {
                return this.shanaField;
            }
            set
            {
                this.shanaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class CreatePkudatZikuyResponse : CreatePkudatYomanResponse
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PkudatYomanShura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PkudatZikuyShura))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class ShuratPkuda
    {
        
        private System.Nullable<int> misparHatamaField;
        
        private System.Nullable<int> asmachtaMishnitField;
        
        private System.Nullable<int> asmachtaRashitField;
        
        private System.Nullable<int> mahutShuraField;
        
        private System.Nullable<long> misparCheshbonField;
        
        private System.Nullable<long> misparCheshbonNegdiField;
        
        private System.Nullable<double> schumField;
        
        private System.Nullable<int> sugMatbeaField;
        
        private string teurField;
        
        private System.Nullable<int> zchutChovaIndField;
        
        private string taarichErechField;
        
        private string taarichRishumField;
        
        private System.Nullable<long> misparCheshbonitField;
        
        private string taarichCheshbonitField;
        
        private System.Nullable<int> sugMaamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> MisparHatama
        {
            get
            {
                return this.misparHatamaField;
            }
            set
            {
                this.misparHatamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> AsmachtaMishnit
        {
            get
            {
                return this.asmachtaMishnitField;
            }
            set
            {
                this.asmachtaMishnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> AsmachtaRashit
        {
            get
            {
                return this.asmachtaRashitField;
            }
            set
            {
                this.asmachtaRashitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> MahutShura
        {
            get
            {
                return this.mahutShuraField;
            }
            set
            {
                this.mahutShuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> MisparCheshbon
        {
            get
            {
                return this.misparCheshbonField;
            }
            set
            {
                this.misparCheshbonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> MisparCheshbonNegdi
        {
            get
            {
                return this.misparCheshbonNegdiField;
            }
            set
            {
                this.misparCheshbonNegdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<double> Schum
        {
            get
            {
                return this.schumField;
            }
            set
            {
                this.schumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> SugMatbea
        {
            get
            {
                return this.sugMatbeaField;
            }
            set
            {
                this.sugMatbeaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Teur
        {
            get
            {
                return this.teurField;
            }
            set
            {
                this.teurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> ZchutChovaInd
        {
            get
            {
                return this.zchutChovaIndField;
            }
            set
            {
                this.zchutChovaIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string TaarichErech
        {
            get
            {
                return this.taarichErechField;
            }
            set
            {
                this.taarichErechField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string TaarichRishum
        {
            get
            {
                return this.taarichRishumField;
            }
            set
            {
                this.taarichRishumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> MisparCheshbonit
        {
            get
            {
                return this.misparCheshbonitField;
            }
            set
            {
                this.misparCheshbonitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string TaarichCheshbonit
        {
            get
            {
                return this.taarichCheshbonitField;
            }
            set
            {
                this.taarichCheshbonitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> SugMaam
        {
            get
            {
                return this.sugMaamField;
            }
            set
            {
                this.sugMaamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class PkudatYomanShura : ShuratPkuda
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class PkudatZikuyShura : ShuratPkuda
    {
        
        private string baitField;
        
        private System.Nullable<int> bankSnifField;
        
        private System.Nullable<int> cheshbonBankField;
        
        private string knisaField;
        
        private System.Nullable<int> kodIshuvField;
        
        private System.Nullable<int> mikudField;
        
        private string rechovField;
        
        private System.Nullable<int> semelRechovField;
        
        private string shemIshuvField;
        
        private string shemMeyuchasField;
        
        private string tevatDoarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Bait
        {
            get
            {
                return this.baitField;
            }
            set
            {
                this.baitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> BankSnif
        {
            get
            {
                return this.bankSnifField;
            }
            set
            {
                this.bankSnifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> CheshbonBank
        {
            get
            {
                return this.cheshbonBankField;
            }
            set
            {
                this.cheshbonBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Knisa
        {
            get
            {
                return this.knisaField;
            }
            set
            {
                this.knisaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> KodIshuv
        {
            get
            {
                return this.kodIshuvField;
            }
            set
            {
                this.kodIshuvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> Mikud
        {
            get
            {
                return this.mikudField;
            }
            set
            {
                this.mikudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Rechov
        {
            get
            {
                return this.rechovField;
            }
            set
            {
                this.rechovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> SemelRechov
        {
            get
            {
                return this.semelRechovField;
            }
            set
            {
                this.semelRechovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ShemIshuv
        {
            get
            {
                return this.shemIshuvField;
            }
            set
            {
                this.shemIshuvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ShemMeyuchas
        {
            get
            {
                return this.shemMeyuchasField;
            }
            set
            {
                this.shemMeyuchasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string TevatDoar
        {
            get
            {
                return this.tevatDoarField;
            }
            set
            {
                this.tevatDoarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePkudatYomanRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePkudatZikuyRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class CreatePkudaRequest
    {
        
        private string emailField;
        
        private System.Nullable<int> goremField;
        
        private System.Nullable<int> makorField;
        
        private System.Nullable<long> misparPkudaField;
        
        private System.Nullable<int> statusField;
        
        private string taarichErechField;
        
        private string taarichRishumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Gorem
        {
            get
            {
                return this.goremField;
            }
            set
            {
                this.goremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Makor
        {
            get
            {
                return this.makorField;
            }
            set
            {
                this.makorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> MisparPkuda
        {
            get
            {
                return this.misparPkudaField;
            }
            set
            {
                this.misparPkudaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string TaarichErech
        {
            get
            {
                return this.taarichErechField;
            }
            set
            {
                this.taarichErechField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string TaarichRishum
        {
            get
            {
                return this.taarichRishumField;
            }
            set
            {
                this.taarichRishumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class CreatePkudatYomanRequest : CreatePkudaRequest
    {
        
        private PkudatYomanShura[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rows", IsNullable=true, Order=0)]
        public PkudatYomanShura[] Rows
        {
            get
            {
                return this.rowsField;
            }
            set
            {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ladpc.fi.pkudot.services")]
    public partial class CreatePkudatZikuyRequest : CreatePkudaRequest
    {
        
        private System.Nullable<long> misparCheshbonField;
        
        private System.Nullable<long> misparCheshbonitField;
        
        private System.Nullable<long> misparCheshbonNegdiField;
        
        private PkudatZikuyShura[] rowsField;
        
        private System.Nullable<int> sugMaamField;
        
        private string taarichCheshbonitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> MisparCheshbon
        {
            get
            {
                return this.misparCheshbonField;
            }
            set
            {
                this.misparCheshbonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> MisparCheshbonit
        {
            get
            {
                return this.misparCheshbonitField;
            }
            set
            {
                this.misparCheshbonitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> MisparCheshbonNegdi
        {
            get
            {
                return this.misparCheshbonNegdiField;
            }
            set
            {
                this.misparCheshbonNegdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rows", IsNullable=true, Order=3)]
        public PkudatZikuyShura[] Rows
        {
            get
            {
                return this.rowsField;
            }
            set
            {
                this.rowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> SugMaam
        {
            get
            {
                return this.sugMaamField;
            }
            set
            {
                this.sugMaamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string TaarichCheshbonit
        {
            get
            {
                return this.taarichCheshbonitField;
            }
            set
            {
                this.taarichCheshbonitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PkudatYomanWSChannel : PkudatYomanWebService.PkudatYomanWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PkudatYomanWSClient : System.ServiceModel.ClientBase<PkudatYomanWebService.PkudatYomanWS>, PkudatYomanWebService.PkudatYomanWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PkudatYomanWSClient() : 
                base(PkudatYomanWSClient.GetDefaultBinding(), PkudatYomanWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PkudatYomanWSSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PkudatYomanWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PkudatYomanWSClient.GetBindingForEndpoint(endpointConfiguration), PkudatYomanWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PkudatYomanWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PkudatYomanWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PkudatYomanWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PkudatYomanWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PkudatYomanWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PkudatYomanWebService.CreatePkudatYomanResponse createPkudatYoman(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatYomanRequest request)
        {
            return base.Channel.createPkudatYoman(systemHeader, request);
        }
        
        public System.Threading.Tasks.Task<PkudatYomanWebService.CreatePkudatYomanResponse> createPkudatYomanAsync(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatYomanRequest request)
        {
            return base.Channel.createPkudatYomanAsync(systemHeader, request);
        }
        
        public PkudatYomanWebService.CreatePkudatZikuyResponse createPkudatZikuy(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatZikuyRequest request)
        {
            return base.Channel.createPkudatZikuy(systemHeader, request);
        }
        
        public System.Threading.Tasks.Task<PkudatYomanWebService.CreatePkudatZikuyResponse> createPkudatZikuyAsync(PkudatYomanWebService.SystemHeader systemHeader, PkudatYomanWebService.CreatePkudatZikuyRequest request)
        {
            return base.Channel.createPkudatZikuyAsync(systemHeader, request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PkudatYomanWSSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PkudatYomanWSSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://vbusuat76.iula.org.il:7021/PkudatYoman_PS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PkudatYomanWSClient.GetBindingForEndpoint(EndpointConfiguration.PkudatYomanWSSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PkudatYomanWSClient.GetEndpointAddress(EndpointConfiguration.PkudatYomanWSSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PkudatYomanWSSoapPort,
        }
    }
}
